name: Check GHDL actions

on: 
  push: 
  schedule:
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        #os: [ubuntu-latest, windows-latest]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
#       - if: ${{ steps.git-cache.outputs.cache-hit != 'true' }}
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true     
      
      - uses: ghdl/setup-ghdl-ci@nightly
        with:
          backend: llvm
      
      - name: Report GHDL
        shell: bash
        run: |
          ghdl --version
          #which ghdl
