name: Build RiscV Toolchain

on: 
  push: 
  schedule:
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build_dep:
    uses: ./.github/workflows/setup_riscv-gnu-toolchain.yml
    #uses: daxzio/setup-eda/.github/workflows/setup_riscv-gnu-toolchain.yml@main
    #with:
    #  githash: "f2a2c87"

  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: [build_dep]
    steps:
      - name: Cache Icarus
        uses: actions/cache@v3
        with:
          path: ${{ needs.build_dep.outputs.cache_dir }}
          key: ${{ needs.build_dep.outputs.cache_key }}
      - name: Add to PATH
        run: |
          echo "${{ needs.build_dep.outputs.cache_dir }}/bin" >> $GITHUB_PATH
      
      - name: Report RiscV
        run: |
          which riscv64-unknown-elf-gcc
