name: Build Verible

on: 
  #push: 
  schedule:
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build_dep:
    uses: ./.github/workflows/setup_verible.yml
    #uses: daxzio/setup-eda/.github/workflows/setup_verible.yml@main
#     with:
#     githash: "dd5e91a4c632b47c8721784e23bf3acc6f46afbc"

  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: [build_dep]
    steps:
      - name: Cache Verible
        uses: actions/cache@v3
        with:
          path: ${{ needs.build_dep.outputs.cache_dir }}
          key: ${{ needs.build_dep.outputs.cache_key }}
      - name: Add to PATH
        run: |
          echo "${{ needs.build.outputs.cache_dir }}/bin" >> $GITHUB_PATH
      
      - name: Report Veriable
        run: |
          which verible-verilog-lint
